# Full Config Template: https://github.com/jekyll/minima/blob/master/_config.yml

# Basic options
title: Romeral's
author: MiguelRomeral
email: miguel.romeral@hotmail.com
description: Miguel Romeral's GitHub page.


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: miguelromeral
    github: miguelromeral
    linkedin: miguelromeral


# Top Navigation Menu
header_pages:
  - cv.md
  - sitemap.md


# Build settings
markdown: kramdown
theme: minima



# theme: jekyll-theme-architect
# remote_theme: jekyll-theme-architect

# # Source: https://github.com/amzn/jekyll-doc-project/blob/master/_config.yml

# title: MiguelRomeral
# description: My developer page with Android, Java, C# and more!

# language: english
# format: web
# favicon: assets/favicon.ico

# show_feedback: true
# feedback_email: miguel.romeral@hotmail.com


# github_button_location_top_navbar: true
# github_button_location_below_title: false
# github_button_location_page_bottom: false

# github_editme_path: https://github.com/miguelromeral

# show_disqus_comments: false

# # Social Sharing
# twitter:
#   username: miguelromeral


# sidebars:
# - nav


# # Defaults
# #defaults:
#   # _docs
# #  - scope:
# #      path: ""
# #      type: docs
# #    values:
# #      sidebar:
# #        nav: "docs"