# Full Config Template: https://github.com/jekyll/minima/blob/master/_config.yml

# Basic options
title: Romeral's Cubicle
author: Miguel Romeral
email: miguel.romeral@hotmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  This is my developer page. Android, Java, C# and more!

show_excerpts: true # set to true to show excerpts on the homepage

twitter_username: miguelromeral
github_username:  miguelromeral
linkedin_username: miguelromeral


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"


# Top Navigation Menu
header_pages:
  - projects.md
  - about.md
  - posts.md
  - sitemap.md

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-seo-tag
