# Full Config Template: https://github.com/jekyll/minima/blob/master/_config.yml

# Basic options
title: MR's Cubicle
author: Miguel Romeral
email: miguel.romeral@hotmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  That's my developer page, with Android, Java, C# and more!

show_excerpts: false # set to true to show excerpts on the homepage


# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll
    rss: rss


# Top Navigation Menu
header_pages:
  - cv.md
  - posts.md
  - sitemap.md


# Build settings
markdown: kramdown
theme: minima