theme: jekyll-theme-architect
remote_theme: jekyll-theme-architect

# Source: https://github.com/amzn/jekyll-doc-project/blob/master/_config.yml

title: MiguelRomeral
description: My developer page: Android, Java, C# and more!

language: english
format: web
favicon: assets/favicon.ico

show_feedback: true
feedback_email: miguel.romeral@hotmail.com


github_button_location_top_navbar: true
github_button_location_below_title: false
github_button_location_page_bottom: false

github_editme_path: https://github.com/miguelromeral

show_disqus_comments: false

